### PR TITLE
Customizable RuleBasedEntityFinder

### PR DESCRIPTION
**Pull request by BeckySharp**
Based on the development in Eidos, we found that being able to customize an entity finder based to a use case is useful.
That said, we still want the easy one that's in place as it works for many usages.
This adds a second class for the customizable aspect, making use of also pushing the `TagSet` class from Eidos up to processors.  Hopefully we can remove it from there and just use this version.

I added some tests, please let me know if more are needed.

@MihaiSurdeanu, @myedibleenso  and @kwalcock please let me know any changes you would like made!

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
LGTM, but why doesn't it compile?

**Comment by kwalcock** [comment]
The testing is performed with both Scala 2.11 and 2.12.  Those dangling commas don't work in Scala 2.11.  I can fix it if someone else doesn't get to it first.

**Comment by BeckySharp** [comment]
i'll see it that was the only one

**Comment by BeckySharp** [comment]
@kwalcock can you please help me? I don't see any other trailing commas and on jenkins i can't see why it doesn't compile

**Comment by kwalcock** [comment]
On Scala 2.11

```

**Comment by kwalcock** [comment]
```
[error] /var/jenkins_home/workspace/processors_rbef/openie/src/main/scala/org/clulab/openie/entities/CustomizableRuleBasedFinder.scala:10:33: object ImplicitConversions is not a member of package scala.collection.convert
[error] import scala.collection.convert.ImplicitConversions.`collection AsScalaIterable`
```

**Comment by kwalcock** [comment]
```
[error] /var/jenkins_home/workspace/processors_rbef/openie/src/main/scala/org/clulab/openie/entities/CustomizableRuleBasedFinder.scala:10:33: object ImplicitConversions is not a member of package scala.collection.convert
[error] import scala.collection.convert.ImplicitConversions.`collection AsScalaIterable`
```

**Comment by kwalcock** [comment]
To check locally, `++2.11.12` in sbt should switch the scala version.  Then compile or test can be run.

**Comment by BeckySharp** [comment]
ok, i'll see if I can figure out how to fix taht one, stack overflow here I
come!

**Comment by BeckySharp** [comment]
is this still waiting on something @MihaiSurdeanu ?

@kwalcock and mihai -- planning on moving the StopwordManager/ing too, heads up

**Comment by MihaiSurdeanu** [comment]
Nope, @kwalcock : can you please merge?

**Comment by BeckySharp** [comment]
cool, I wanna use it for the stop stuff that I'm doing en ce moment
